### ISSUE TITLE
Consulting doubts

### ISSUE THREAD

**Issue by YZ20211221** [gywns6287/deepGBLUP#1]
Hi, thank you so much for your outstanding work. I was reading through your code and noticed that the current deepGBLUP seems to only use the pytorch part and doesn't incorporate the a, d, and e parts of GBLUP?Where is the part where GBLUP merges with Deep learning networks? Where is the part where GBLUP integrates with Deep learning networks?

**Comment by gywns6287** [comment]
a, d, and e are calculated in the dataloader

https://github.com/gywns6287/deepGBLUP/blob/e9e8beb9f37ef7c8a0c735b80ef0a9f060e2bba5/dataset.py#L83-L85

 and they are incorporated in the test stage
https://github.com/gywns6287/deepGBLUP/blob/e9e8beb9f37ef7c8a0c735b80ef0a9f060e2bba5/train_test.py#L66-L69

**Comment by YZ20211221** [comment]
thank you

**Comment by YZ20211221** [comment]
Would like to ask you one more question.

May I ask if you have tested it on the cattle dataset only? I found that it didn't show good results on some crop datasets? I wonder if I'm using it wrong?

**Comment by YZ20211221** [comment]
> a, d, and e are calculated in the dataloader
> 
> https://github.com/gywns6287/deepGBLUP/blob/e9e8beb9f37ef7c8a0c735b80ef0a9f060e2bba5/dataset.py#L83-L85
> 
> and they are incorporated in the test stage
> 
> https://github.com/gywns6287/deepGBLUP/blob/e9e8beb9f37ef7c8a0c735b80ef0a9f060e2bba5/train_test.py#L66-L69

Would like to ask you one more question.

May I ask if you have tested it on the cattle dataset only? I found that it didn't show good results on some crop datasets? I wonder if I'm using it wrong?
